spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    #host: 127.0.0.1 # RabbitMQ 服务的地址
    #port: 5672 # RabbitMQ 服务的端口
    # 集群节点
    addresses: proxy.heqin.aliyun.com:5672,proxy.heqin.aliyun.com:5673,proxy.heqin.aliyun.com:5674
    username: admin # RabbitMQ 服务的账号
    password: pass.123 # RabbitMQ 服务的密码
    publisher-confirm-type: correlated # 设置 Confirm 类型为 CORRELATED 。
    publisher-returns: true #

logging:
  level:
    root: INFO #没有特殊设置日志级别的包名，则使用这边的日志级别
    cn:
      iocoder: INFO # cn.iocoder 限制打印 INFO 级别
  pattern:
    #console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{30} - %msg%n)'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{TRACE_ID}] %logger{300} - %msg%n'


#mdc实现全链路调用日志跟踪
mcdWholeLinkLogTrace:
  # 拦截实现方式 Aop、Filter、Interceptor
  interceptWay: Interceptor
