spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
#    host: 127.0.0.1 # RabbitMQ 服务的地址
#    port: 5672 # RabbitMQ 服务的端口
    # 集群节点
    addresses: proxy.heqin.aliyun.com:5672,proxy.heqin.aliyun.com:5673,proxy.heqin.aliyun.com:5674
    username: admin # RabbitMQ 服务的账号
    password: pass.123 # RabbitMQ 服务的密码
    listener:
      simple:
        acknowledge-mode: manual # 配置 Consumer 手动提交
