#spring:
#  application:
#    name: demo-provider # Spring 应用名
#  cloud:
#    zookeeper:
#      #指定zookeeper的地址,多个用逗号拼接
#      connect-string: proxy.heqin.aliyun.com:2181,proxy.heqin.aliyun.com:2182,proxy.heqin.aliyun.com:2183
#      # Zookeeper 作为注册中心的配置项，对应 ZookeeperDiscoveryProperties 配置类
#      discovery:
#        root: /services # Zookeeper 数据存储的根节点，默认为 /services
#
#server:
#  port: 18080 # 服务器端口。默认为 8080
spring:
  profiles:
    active: dev #[多环境配置](https://www.iocoder.cn/Spring-Boot/config-file/)
